import type { PhotoSpecification } from './types'

export const specifications: PhotoSpecification[] = [
  {
    id: 'cn-id-1inch',
    name: '一寸照片',
    category: '常用尺寸',
    widthMm: 25,
    heightMm: 35,
    widthPx: 295,
    heightPx: 413,
    dpi: 300,
    maxKb: 200,
    backgrounds: ['#ffffff', '#438edb', '#ff0000'],
    featured: true,
  },
  {
    id: 'cn-id-2inch',
    name: '二寸照片',
    category: '常用尺寸',
    widthMm: 35,
    heightMm: 49,
    widthPx: 413,
    heightPx: 579,
    dpi: 300,
    maxKb: 200,
    backgrounds: ['#ffffff', '#438edb', '#ff0000'],
    featured: true,
  },
  {
    id: 'cn-id-small-2inch',
    name: '小二寸照片',
    category: '常用尺寸',
    widthMm: 33,
    heightMm: 48,
    widthPx: 390,
    heightPx: 567,
    dpi: 300,
    maxKb: 200,
    backgrounds: ['#ffffff', '#438edb', '#ff0000'],
    featured: true,
  },
  {
    id: 'cn-passport',
    name: '护照签证照',
    category: '出入境',
    widthMm: 33,
    heightMm: 48,
    widthPx: 390,
    heightPx: 567,
    dpi: 300,
    backgrounds: ['#ffffff'],
    featured: true,
  },
  {
    id: 'cn-id-card',
    name: '身份证照片',
    category: '证件',
    widthMm: 26,
    heightMm: 32,
    widthPx: 358,
    heightPx: 441,
    dpi: 350,
    backgrounds: ['#ffffff'],
    featured: true,
  },
  {
    id: 'cn-driver-license',
    name: '驾驶证照片',
    category: '证件',
    widthMm: 22,
    heightMm: 32,
    widthPx: 260,
    heightPx: 378,
    dpi: 300,
    backgrounds: ['#ffffff'],
  },
  {
    id: 'cn-ntce',
    name: '教师资格证',
    category: '考试',
    widthMm: 25,
    heightMm: 35,
    widthPx: 295,
    heightPx: 413,
    dpi: 300,
    minKb: 15,
    maxKb: 200,
    backgrounds: ['#ffffff'],
  },
  {
    id: 'cn-cet',
    name: '四六级考试',
    category: '考试',
    widthMm: 33,
    heightMm: 48,
    widthPx: 240,
    heightPx: 320,
    dpi: 180,
    minKb: 20,
    maxKb: 200,
    backgrounds: ['#438edb'],
  },
]
